.travis.yml
README.md
build/Makefile
build/assets/README.md
build/build.sh
build/versions

- move agent & JRE versions into `build/versions` file
- use master tag to provide bundle version on deploy

Agent & JRE versions from file

---

.travis.yml
README.md
build/Makefile
build/assets/README.md
build/build.sh
build/versions

- store secrets instead of using `travis env`
- trigger build on pr (still master-tag ie gh-release required to trigger deploy)

Setup Travis properly

---

build/versions

Updated:
- `nri-discovery-kubernetes` to `v1.1.0`
- `nri-couchbase` to `v2.3.6`
- `nri-kafka` to `v2.12.0`
- `nri-nginx` to `v2.0.1`
- `nri-postgresql` to `v2.3.2`
- `nri-postgresql` to `v2.3.2`
- `nri-rabbitmq` to `v2.2.2`

Update on-host integrations to latest versions.

---

build/Dockerfile

This justs adds the passthrough to make the integration work, we will be adding the integration on a following PR.

Add the passthrough for the ecs integration

---

build/versions

Update infrastructure agent [v1.13.2](https://github.com/newrelic/infrastructure-agent/releases/tag/1.13.2)
Update nri-cassandra [v2.6.0](https://github.com/newrelic/nri-cassandra/releases/tag/v2.6.0)
Update nri-discovery-kubernetes [v1.3.0](https://github.com/newrelic/nri-discovery-kubernetes/releases/tag/v1.3.0)

chore: update build versions

---

build/Dockerfile
build/versions

This reverts commit 3776205bb74ab0aeed184c79f1bf5a6825135dbd, reversing
changes made to 9ac1795152e9500464cb333a38ab94b38988bbcc. See https://github.com/newrelic/infrastructure-bundle/pull/46
It should fix broken nrjmx tool.

Revert "Merge pull request #46 from newrelic/croman/nrjmx-jdk-update"

---

.github/workflows/build.yml

Previous CI pipeline ran two different snyk checks, one being unreadable and the other having wrong arguments.
This PR moves to the Snyk action, with correct arguments.

ci: use updated snyk action

---

bundle.yml

Updated Integration services  in this PR make use of the v3.6.7 Infrastructure SDK

update version of integration services

---

bundle.yml

`nri-oracledb` uses [godror](https://github.com/godror/godror), which itself needs the [oracle client library](https://oracle.github.io/odpi/doc/installation.html) installed on the running host in order to work properly.
Since this library is not included in the infrastructure-bundle, it doesn't make sense to include `nri-oracledb` in it.

Remove nri-oracledb

---

bundle.yml

This release includes a new version of JMXTerm, with patches for some security vulnerabilities.

bundle/nrjmx: upgrade to 1.5.3

---

.gitignore
bundle.yml

- chore: bump agent version 1.19.2
- feat: gitignore vendor and build

Bump agent version

---

bundle.yml

Staging s3 bucket/repo is not considered stable, since we often overwrite it with a copy of the production repo. This can cause the downloader to fail, because a prerelease that exists in GitHub is not found in the s3 repo.
With this change, prereleases will be downloaded directly from GitHub releases.

bundle.yml: use github as stagingUrl

---

bundle.yml
downloader.go

This makes the contents of bundle.yml consistent with the tags and release names used in GitHub, allowing for easier comparison and replacement.
A template helper function, trimv, has been added to remove the leading v from name templates.

downloader: make integration versions start with v

---

README.md

`repolinter` still complaining about the header.

fix repolinter issue within README file

---

bundle.yml
downloader.go

`testFiles` is a template-enabled array that the downloader program will iterate over, checking for existence of the files for all downloaded integrations. This can be a basic sanity self-check for broken prereleases (or downloader itself).
As usual `testFiles` can be defined globally, in which case it will be extended for all the integrations (leveraging templating), but also individually per-integration. If both are specified, the array local to the integration takes precedence and the globally-defined entry will be ignored.
Additionally, in this PR the template-building logic has been extracted to a different method to improve readability.
Since the override check is done by seeing if the `testFiles` entry is defined (non-empty) for an integration, it is currently not possible to set …

downloader: implement support for testFiles config entry

---

bundle.yml

Since nri-ecs integration does not generate more packages on releases (now it has it's own image) the nightly workflows [fails](https://github.com/newrelic/infrastructure-bundle/runs/4160576873?check_suite_focus=true#step:7:61) when a new release of this integration is created. 
This will be a temporal workaround until nri-ecs is removed from the bundle #130 , which it needs to wait until Product confirmation.

fix: use fixed staging url for nri-ecs

---

Dockerfile
bundle.yml

Since `nri-ecs` integration will be having it's own image based on the bundle, this PR removes the integration.
Also removes the ECS related configuration (metadata uri and Fargate) passthrough environment since this is already added during [installation](https://github.com/newrelic/nri-ecs/blob/main/deploy/fargate_sidecar_example.json#L39) of the ECS integration.
Installations of ECS cluster that points to the `latest` image of the bundle will break after this PR is relased.
This release needs to be done after the `nri-ecs` image is released and existing customers pointing to `latest` bundle running ecs integration are notified.
- Removes the `nri-ecs` integration. This integration has its own image `newrelic/nri-ecs` from `v1.4.0` which is based on the `infrastructure-bundle` image, but …

chore: remove nri-ecs

---

bundle.yml

`nri-varnish` cannot run inside the container since it uses the `varnishstats` cli tool. The integration doesn't have any documentation to run in containerized environment for this reason.

delete nri-varnish integration

---

.github/workflows/security.yml

This PR will cause trivy to neither report nor fail vulns that are not flagged as CRITICAL. This aims to reduce the noise of the security workflow by making it adhere better to our current policies, instead of taking for granted it will always be red and therefore never checking what it is actually saying.

ci/security: make trivy fail on CRITICALs only

---

.github/workflows/security.yml

We have been using trivy on this repo for a while, but we haven't been submitting its output to Github's built-in security dashboard.
This PR attems to fix that using [GitHub's instructions](https://github.com/newrelic/infrastructure-bundle/new/master?filename=.github%2Fworkflows%2Ftrivy.yml&workflow_template=code-scanning%2Ftrivy) as a base.

ci: generate a security report using trivy

---

bundle.yml

nri-snmp integration is eol, not maintained.

remove nri-snmp integration

---

.github/renovate.json5

It is a copy and paste from the already working `nri-kafka` configuration removing the `sarama` dependency.: https://github.com/newrelic/nri-kafka/blob/master/renovate.json5#L12-L23
I also removed rules to group dependencies as they do not make sense anymore as we would want to fail individually.

Configure automerge for renovatebot (NR-107049)

---

.github/workflows/release.yml

RT generates the version with the `v` prefix which is used as a TAG. The PR just modify the check on the format but
the prefix is **still removed** for tagging the image.

allow v prefix on tag name

---

.github/workflows/security.yml

This step was skipped for the renovate branches that didn't create pull requests.

Run Trivy step on renovate branches (NR-119198)

---

.github/workflows/nightly.yml
docker-build.sh
downloader.go

This change allows us to have the nightly build with the latest agent version as base.
This is useful for our canaries
Example:
```
export AGENT_VERSION=`go run ./downloader.go -agent-version-latest `        
./docker-build.sh . --push
2024/02/19 18:03:38 infrastructure-agent 1.48.4 -> 1.49.0
Building the image leveraging agent_version=1.49.0
[...]
```
```
export AGENT_VERSION=`go run ./downloader.go -agent-version-latest -staging`
./docker-build.sh . --push
2024/02/19 18:03:29 Fetching releases for infrastructure-agent...
2024/02/19 18:03:34 infrastructure-agent 1.48.4 -> 1.49.1
Building the image leveraging agent_version=1.49.1-rc
[...]
```

feat(latestAgent): use latest agent in nightly

---

.github/workflows/nightly.yml

Nightly build's security scanning was set up to continue on errors and we don't want that (that's why we set up notifications [here](https://github.com/newrelic/infrastructure-bundle/pull/436)). This disables that.

ci: fail on nightly build on detected vulnerabilities

---

.github/workflows/nightly.yml
.github/workflows/on-demand.yml
.github/workflows/security.yml

We were rate-limited pretty quickly with the latest changes that attempt to download the CVE database every time, so let's enable the cache again and see if the updated action version works better with it from now on.

ci: enable trivy action cache

---

.github/workflows/nightly.yml

Trivy reporting vulnerabilities is preventing the nightly builds from being pushed due to the [failures now interrupting the job](https://github.com/newrelic/infrastructure-bundle/pull/440).
See the **LAST PUSHED** field in the screenshot:
This fixes that making the trivy check the last thing that is done on the nightly job.

ci: run trivy after pushing nightly build

---

.github/workflows/security.yml

The reusable security workflow (https://github.com/newrelic/coreint-automation/blob/8e5f750ba1e151b93454c56aeb1f6dbcea0e3b00/.github/workflows/reusable_security.yaml) scans the repo ( codebase ) for vulnerabilities with Trivy.
This cannot be used for `infrastructure-bundle` because we need to build a docker Image and then scan that docker image for vulnerabilities by running trivy in table-mode.
We have code that does this in the reusable nightly workflow for docker images. But that workflow also publishes the nightly build so reusing it just to scan the image on pull request does not make sense.
The code that runs the security check on a schedule can be removed because that is being handled by the nightly.
The code that runs the security check on a pull request should be left as is since …

security workflow does not repeat nightly scans

---

.github/workflows/release.yml
.github/workflows/security.yml

Tested prerelease / release successfully with the new reusable workflow.
Merge only after this: https://github.com/newrelic/coreint-automation/pull/103

Nr 341876 make docker images pre release uniform

---

.github/workflows/nightly.yml
.github/workflows/release.yml

Pass slack channel and and slack token as secrets to the reusable nightly and image release workflows.

slack channel and token are passed as secrets

---

.github/workflows/nightly_candidate.yml

- add nightly candidate workflow, which will have latest agent version and all stating integration versions

ci : nightly candidate workflow

---

.github/workflows/build.yml
.github/workflows/nightly.yml
.github/workflows/on-demand.yml
.github/workflows/release.yml
.gitignore
CHANGELOG.md
Dockerfile
bundle-fips.yml
docker-build.sh
run-fips-ci-locally.sh

Changes in this PRs - Build a fips compliant image `infrastructure-bundle-fips` which contains all fips complaint integrations and infra-agent.
<details><summary>Local Testing of building infrastructure-bundle-fips image</summary>
<p>
```shell
saanamsairajyadav@FDJV7H6TVP infrastructure-bundle % ./run-fips-ci-locally.sh
Downloading integrations...
2025/05/02 13:19:55 Downloading https://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/nri-apache-fips_linux_1.14.0_amd64.tar.gz
2025/05/02 13:19:55 Downloading https://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/nri-couchbase-fips_linux_2.8.0_amd64.tar.gz
2025/05/02 13:19:55 Downloading https://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/nri-consul-fips_linux_2.9.0_amd64.tar.gz
2025/05/02 …
```

feat(fips): add fips compliant image

---

.github/workflows/release.yml
CHANGELOG.md

Publishing images for infrastructure bundle fips was broken due the docker image env variable not being passed correctly.
This PR passes that and fixes this issue.

Fix: FIPS image tags publishing for pre releases
